version: "2"
linters:
  enable:
    - errname
    - gocheckcompilerdirectives
    - gocyclo
    - godot
    - lll
    - makezero
    - unparam
  settings:
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 79
      tab-width: 4
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        source: 'defer '
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
