name: update
on:
  schedule:
    - cron: "21 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  op:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0 # https://github.com/actions/checkout/issues/1471
      - uses: actions/setup-go@v5
      - run: '"$(wget -O- lesiw.io/op | sh)" update'
